services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: arboris_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  python_server:
    build:
      context: .
      dockerfile: docker/python_server.dockerfile
    container_name: arboris_python
    restart: always
    environment:
      PYTHON_SERVER_HOST: ${PYTHON_SERVER_HOST}
      PYTHON_SERVER_PORT: ${PYTHON_SERVER_PORT}
    ports:
      - "${PYTHON_SERVER_PORT}:${PYTHON_SERVER_PORT}"
    depends_on:
      postgres:
        condition: service_healthy

  go_server:
    build:
      context: .
      dockerfile: docker/go_server.dockerfile
    container_name: arboris_go
    restart: always
    environment:
      GO_SERVER_HOST: ${GO_SERVER_HOST}
      GO_SERVER_PORT: ${GO_SERVER_PORT}

      PYTHON_SERVER_HOST: "python_server"
      PYTHON_SERVER_PORT: ${PYTHON_SERVER_PORT}

      WEBHOOK_BURST_RATE: ${WEBHOOK_BURST_RATE}
      WEBHOOK_RATE_LIMIT: ${WEBHOOK_RATE_LIMIT}
      WEBHOOK_MAX_PAYLOAD_SIZE: ${WEBHOOK_MAX_PAYLOAD_SIZE}

      GITHUB_WEBHOOK_SECRET: ${GITHUB_WEBHOOK_SECRET}

      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${GO_SERVER_PORT}:${GO_SERVER_PORT}"
    depends_on:
      python_server:
        condition: service_started
      postgres:
        condition: service_healthy

volumes:
  postgres_data: